# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AssessmentTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Toast-Swift', '~> 5.0.0'

  # Pods for AssessmentTest

  target 'AssessmentTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AssessmentTestUITests' do
    # Pods for testing
  end

end
